#ifndef AGENDASERVICE_GLOBAL_H
#define AGENDASERVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AGENDASERVICE_LIBRARY)
#  define AGENDASERVICESHARED_EXPORT Q_DECL_EXPORT
#else
#  define AGENDASERVICESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // AGENDASERVICE_GLOBAL_H
